# Generated by Django 4.2.7 on 2016-07-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_address_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='profile_image/%Y/%m/%d/'),
        ),
    ]
