# Generated by Django 4.2.7 on 2016-05-22 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='total_price',
        ),
    ]
