# Generated by Django 4.2.7 on 2016-07-16 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_product_sell'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_favourite',
            field=models.IntegerField(default=0),
        ),
    ]
